TTTController Class Reference
The TTTController class is the controller for a Tic Tac Toe game, it takes in game options as input, and controls the view (TicTacToeGame) and the model (Board) according to the game logic specified in this class, it is also responsible for calling the AI agent to play its turn if specified by the game options.
#include <TTTController.h>
Public Slots
virtual void updateGame (Cell &cell)
updateGame sets the cell clicked in the model (board).
Signals
void AIFinished ()
turnFinished is emitted when the human player is finished with the cell input, and the internal game state is supposed to be updated.
void humanFinished ()
void speechRecognized (QString)
Public Member Functions
TTTController (const TTTOptions &options, QObject *parent=nullptr)
TTTController constructs a game controller.
virtual void startGame ()
startGame executes this QDialog to show the GUI and start the gameplay.
int parseSpeechToCell (const QString &text)
QWidget * getView ()
Protected Member Functions
virtual void updateGameState (Cell &cell)
updateGameState updates the view and the model and switches the current player.
virtual void AIAgentPlay ()
AIAgentPlay calls the AI agent to play given the current board inputs.
virtual void HumanPlay ()
HumanPlay calls the Speech Recognition Engine for decoding input into Cell.
virtual void switchPlayer ()
switchPlayer switches the current player mark (X to O and O to X).
Protected Attributes
TicTacToeGame view_
view is the view class of a tic tac toe game.
Board board_
board is the model that represents the underlying layer of a game.
vector< Cell > cells_
cells are the collection of cell buttons built by the view class.
const TTTOptions & options_
options is the collection of values and flags that controls the game.
BoardMarks currentPlayer_
currentPlayer is the player that will play the current turn.
unique_ptr< AIAgent > agent_
agent is the AI agent chosen to play against the human player.
Private Slots
void onSpeechRecognized (const QString &text)
void onSocketReadyRead ()
Private Member Functions
void setConnections ()
setConnections will set a connection to all GUI elements to slots defined to handle these events.
void reset ()
resets all internal components, the view, the model and the AI agent. then if AI is supposed to start a game it will play first.
void setupNetwork ()
void sendMove (int row, int col, char player)
Private Attributes
QTcpSocket * socket_
Detailed Description
The TTTController class is the controller for a Tic Tac Toe game, it takes in game options as input, and controls the view (TicTacToeGame) and the model (Board) according to the game logic specified in this class, it is also responsible for calling the AI agent to play its turn if specified by the game options.
Constructor & Destructor Documentation
TTTController()
TTTController::TTTController (const TTTOptions & options, QObject * parent = nullptr) [explicit]
TTTController constructs a game controller.
Parameters
options is the collection of values and flags that controls the game.
parent is a QObject type parent that owns this instance of the controller.
References agent_, board_, TTTOptions::boardSize, cells_, currentPlayer_, O, options_, reset(), setConnections(), view_, and X.
Member Function Documentation
AIAgentPlay()
void TTTController::AIAgentPlay () [protected], [virtual]
AIAgentPlay calls the AI agent to play given the current board inputs.
References agent_, board_, cells_, Cell::col, currentPlayer_, defaults::INVALID_CELL, Cell::row, and updateGame().
Referenced by reset(), and setConnections().
AIFinished
void TTTController::AIFinished () [signal]
turnFinished is emitted when the human player is finished with the cell input, and the internal game state is supposed to be updated.
Referenced by onSocketReadyRead(), and setConnections().
getView()
QWidget * TTTController::getView () [inline]
References view_.
humanFinished
void TTTController::humanFinished () [signal]
Referenced by onSocketReadyRead(), and setConnections().
HumanPlay()
void TTTController::HumanPlay () [protected], [virtual]
HumanPlay calls the Speech Recognition Engine for decoding input into Cell.
References SpeechToText::configuration(), SpeechToText::free(), SpeechToText::hyp, SpeechToText::init(), SpeechToText::listen(), and speechRecognized().
Referenced by onSpeechRecognized(), reset(), and setConnections().
onSocketReadyRead
void TTTController::onSocketReadyRead () [private], [slot]
References AIFinished(), currentPlayer_, humanFinished(), O, options_, socket_, switchPlayer(), and X.
Referenced by NetworkManager::NetworkManager(), and setupNetwork().
onSpeechRecognized
void TTTController::onSpeechRecognized (const QString & text) [private], [slot]
References cells_, HumanPlay(), defaults::INVALID_CELL, parseSpeechToCell(), and updateGame().
Referenced by setConnections().
parseSpeechToCell()
int TTTController::parseSpeechToCell (const QString & text) [inline]
References defaults::INVALID_CELL.
Referenced by onSpeechRecognized().
reset()
void TTTController::reset () [private]
resets all internal components, the view, the model and the AI agent. then if AI is supposed to start a game it will play first.
References agent_, AIAgentPlay(), board_, cells_, currentPlayer_, HumanPlay(), options_, view_, and X.
Referenced by setConnections(), and TTTController().
sendMove()
void TTTController::sendMove (int row, int col, char player) [private]
References socket_.
Referenced by updateGame().
setConnections()
void TTTController::setConnections () [private]
setConnections will set a connection to all GUI elements to slots defined to handle these events.
References AIAgentPlay(), AIFinished(), humanFinished(), HumanPlay(), TicTacToeGame::newGame(), onSpeechRecognized(), reset(), setupNetwork(), speechRecognized(), and view_.
Referenced by TTTController().
setupNetwork()
void TTTController::setupNetwork () [private]
References onSocketReadyRead(), and socket_.
Referenced by setConnections().
speechRecognized
void TTTController::speechRecognized (QString) [signal]
Referenced by HumanPlay(), and setConnections().
startGame()
void TTTController::startGame () [virtual]
startGame executes this QDialog to show the GUI and start the gameplay.
References view_.
switchPlayer()
void TTTController::switchPlayer () [protected], [virtual]
switchPlayer switches the current player mark (X to O and O to X).
References currentPlayer_, O, and X.
Referenced by onSocketReadyRead().
updateGame
void TTTController::updateGame (Cell & cell) [virtual], [slot]
updateGame sets the cell clicked in the model (board).
Parameters
cell the clicked cell that the player chooses.
References board_, Cell::col, currentPlayer_, Cell::row, sendMove(), updateGameState(), and X.
Referenced by AIAgentPlay(), and onSpeechRecognized().
updateGameState()
void TTTController::updateGameState (Cell & cell) [protected], [virtual]
updateGameState updates the view and the model and switches the current player.
Parameters
cell the clicked cell that the player chooses.
References board_, currentPlayer_, NoWinner, view_, and X.
Referenced by updateGame().
Member Data Documentation
agent_
unique_ptr<AIAgent> TTTController::agent_ [protected]
agent is the AI agent chosen to play against the human player.
Referenced by AIAgentPlay(), reset(), and TTTController().
board_
Board TTTController::board_ [protected]
board is the model that represents the underlying layer of a game.
Referenced by AIAgentPlay(), reset(), TTTController(), updateGame(), and updateGameState().
cells_
vector<Cell> TTTController::cells_ [protected]
cells are the collection of cell buttons built by the view class.
Referenced by AIAgentPlay(), onSpeechRecognized(), reset(), and TTTController().
currentPlayer_
BoardMarks TTTController::currentPlayer_ [protected]
currentPlayer is the player that will play the current turn.
Referenced by AIAgentPlay(), onSocketReadyRead(), reset(), switchPlayer(), TTTController(), updateGame(), and updateGameState().
options_
const TTTOptions& TTTController::options_ [protected]
options is the collection of values and flags that controls the game.
Referenced by onSocketReadyRead(), reset(), and TTTController().
socket_
QTcpSocket* TTTController::socket_ [private]
Referenced by onSocketReadyRead(), sendMove(), and setupNetwork().
view_
TicTacToeGame TTTController::view_ [protected]
view is the view class of a tic tac toe game.
Referenced by getView(), reset(), setConnections(), startGame(), TTTController(), and updateGameState().
The documentation for this class was generated from the following files:
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/Controller/TTTController.h
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/Controller/TTTController.cpp