MiniMaxAgent Class Reference
The MiniMaxAgent class handles all the logic of picking a cell based on the MiniMax Algorithm.
#include <MiniMaxAgent.h>
Public Member Functions
MiniMaxAgent (QObject *parent=nullptr, unsigned short depth, BoardMarks AImark)
MiniMaxAgent: a constructor function that creates the MiniMax Agent.
int play () override
Start the minimax algorithm to choose a cell to play based on a given board.
Private Member Functions
short maxMove (Board &board, unsigned short depth, short alpha, short beta) const
maxMove simulates the AI choice based on the final game states, as it wants to win it will choose the maximum score of each simulated move.
short minMove (Board &board, unsigned short depth, short alpha, short beta) const
minMove simulates the player choice based on the final game states, as it wants to win it will choose the minimum score of each simulated move.
short score (const BoardState state) const
score associates a score to the final states of a game.
Private Attributes
const unsigned short depth_
depth cutoff of the minimax algorithm's search tree.
const BoardMarks AImark_
The mark (X or O) of the AI.
const BoardMarks playerMark_
The mark (X or O) of the human player.
Static Private Attributes
static constexpr short AI_WIN_SCORE = 1
AI_WIN_SCORE defines the score of the final board when the AI wins.
static constexpr short PLAYER_WIN_SCORE = -1
PLAYER_WIN_SCORE defines the score of the final board when the human player wins.
static constexpr short TIE_SCORE = 0
TIE_SCORE defines the score of the final board when the the game is a tie.
Detailed Description
The MiniMaxAgent class handles all the logic of picking a cell based on the MiniMax Algorithm.
It simulates all possible plays taking turns simulating an AI turn then a Player turn until a final state is reached, then it scores the final state by giving a negative value if the Player wins and a positive value if it wins, then backtracks picking the minimum score if it is the player turn and the max score if its the AI turn.
Constructor & Destructor Documentation
MiniMaxAgent()
MiniMaxAgent::MiniMaxAgent (QObject * parent = nullptr, unsigned short depth, BoardMarks AImark)
MiniMaxAgent: a constructor function that creates the MiniMax Agent.
Parameters
depth cutoff of the minimax algorithm's search tree.
AImark The mark (X or O) of the AI.
playerMark The mark (X or O) of the human player.
References AImark_, depth_, and playerMark_.
Member Function Documentation
maxMove()
short MiniMaxAgent::maxMove (Board & board, unsigned short depth, short alpha, short beta) const [private]
maxMove simulates the AI choice based on the final game states, as it wants to win it will choose the maximum score of each simulated move.
Parameters
board a reference to the board model.
depth The current depth of the search tree.
alpha The minimum score that the maximizing player is assured of.
beta The maximum score that the minimizing player is assured of.
Returns
References AImark_, Board::at(), Empty, Board::evaluateBoard(), minMove(), NoWinner, Board::resetCell(), score(), Board::setPlayerInput(), and Board::size().
Referenced by minMove().
minMove()
short MiniMaxAgent::minMove (Board & board, unsigned short depth, short alpha, short beta) const [private]
minMove simulates the player choice based on the final game states, as it wants to win it will choose the minimum score of each simulated move.
Parameters
board a reference to the board model.
depth The current depth of the search tree.
alpha The minimum score that the maximizing player is assured of.
beta The maximum score that the minimizing player is assured of.
Returns
References Board::at(), Empty, Board::evaluateBoard(), maxMove(), NoWinner, playerMark_, Board::resetCell(), score(), Board::setPlayerInput(), and Board::size().
Referenced by maxMove(), and play().
play()
int MiniMaxAgent::play () [override]
Start the minimax algorithm to choose a cell to play based on a given board.
Parameters
board a reference to the board model.
Returns
the chosen cell index (in a 1D array) that the AI played.
References AImark_, Board::at(), depth_, Empty, Board::evaluateBoard(), defaults::INVALID_CELL, minMove(), NoWinner, Board::resetCell(), Board::setPlayerInput(), and Board::size().
Referenced by TEST(), TEST(), TEST(), and TEST().
score()
short MiniMaxAgent::score (const BoardState state) const [private]
score associates a score to the final states of a game.
Parameters
state is an input paramater that specifies the state of the game.
Returns
a score based on the state of the game.
References AI_WIN_SCORE, AImark_, O, OWins, PLAYER_WIN_SCORE, TIE_SCORE, X, and XWins.
Referenced by maxMove(), and minMove().
Member Data Documentation
AI_WIN_SCORE
short MiniMaxAgent::AI_WIN_SCORE = 1 [static], [constexpr], [private]
AI_WIN_SCORE defines the score of the final board when the AI wins.
Referenced by score().
AImark_
const BoardMarks MiniMaxAgent::AImark_ [private]
The mark (X or O) of the AI.
Referenced by maxMove(), MiniMaxAgent(), play(), and score().
depth_
const unsigned short MiniMaxAgent::depth_ [private]
depth cutoff of the minimax algorithm's search tree.
Referenced by MiniMaxAgent(), and play().
PLAYER_WIN_SCORE
short MiniMaxAgent::PLAYER_WIN_SCORE = -1 [static], [constexpr], [private]
PLAYER_WIN_SCORE defines the score of the final board when the human player wins.
Referenced by score().
playerMark_
const BoardMarks MiniMaxAgent::playerMark_ [private]
The mark (X or O) of the human player.
Referenced by MiniMaxAgent(), and minMove().
TIE_SCORE
short MiniMaxAgent::TIE_SCORE = 0 [static], [constexpr], [private]
TIE_SCORE defines the score of the final board when the the game is a tie.
Referenced by score().
The documentation for this class was generated from the following files:
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/AI/MiniMaxAgent.h
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/AI/MiniMaxAgent.cpp