SpeechManager Class Reference
#include <SpeechManager.h>
Signals
void speechRecognized (const QString &text)
void speechReadyToProcess (const char *hyp)
Public Member Functions
SpeechManager (QObject *parent=nullptr)
~SpeechManager ()
void configure ()
void init ()
void startListening ()
Private Slots
void processRecognitionResult (const char *hyp)
Private Member Functions
bool hypIsValid ()
void freeHeap ()
Private Attributes
PaStream * stream_
PaError err_
ps_decoder_t * decoder_
ps_config_t * config_
ps_endpointer_t * ep_
short * frame_
size_t frame_size_
const char * hyp_
Constructor & Destructor Documentation
SpeechManager()
SpeechManager::SpeechManager (QObject * parent = nullptr) [explicit]
DEV-SPEECH-0003 @title SpeechManager bloquea el hilo principal Solved @severity High ratty SpeechManager debe moverse a QThread TASK-THREAD-0002
References config_, decoder_, ep_, frame_, frame_size_, processRecognitionResult(), speechReadyToProcess(), speechRecognized(), and stream_.
~SpeechManager()
SpeechManager::~SpeechManager ()
References freeHeap().
Member Function Documentation
configure()
void SpeechManager::configure ()
References config_, and ConfigManager::instance().
freeHeap()
void SpeechManager::freeHeap () [private]
References decoder_, and ep_.
Referenced by ~SpeechManager().
hypIsValid()
bool SpeechManager::hypIsValid () [private]
References hyp_.
Referenced by startListening().
init()
void SpeechManager::init ()
References E_FATAL, E_FATAL_SYSTEM, NULL, ps_endpointer_frame_size, and PS_VAD_LOOSE.
processRecognitionResult
void SpeechManager::processRecognitionResult (const char * hyp) [private], [slot]
Referenced by SpeechManager().
speechReadyToProcess
void SpeechManager::speechReadyToProcess (const char * hyp) [signal]
Referenced by SpeechManager().
speechRecognized
void SpeechManager::speechRecognized (const QString & text) [signal]
Referenced by SpeechManager().
startListening()
void SpeechManager::startListening ()
References E_ERROR, E_FATAL, FALSE, hypIsValid(), and NULL.
Member Data Documentation
config_
ps_config_t* SpeechManager::config_ [private]
Referenced by configure(), and SpeechManager().
decoder_
ps_decoder_t* SpeechManager::decoder_ [private]
Referenced by freeHeap(), and SpeechManager().
ep_
ps_endpointer_t* SpeechManager::ep_ [private]
Referenced by freeHeap(), and SpeechManager().
err_
PaError SpeechManager::err_ [private]
frame_
short* SpeechManager::frame_ [private]
Referenced by SpeechManager().
frame_size_
size_t SpeechManager::frame_size_ [private]
Referenced by SpeechManager().
hyp_
const char* SpeechManager::hyp_ [private]
Referenced by hypIsValid().
stream_
PaStream* SpeechManager::stream_ [private]
Referenced by SpeechManager().
The documentation for this class was generated from the following files:
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/Speech/SpeechManager.h
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/Speech/SpeechManager.cpp