NetworkManager Class Reference
#include <NetworkManager.h>
Signals
void connected ()
void disconnected ()
void errorOccurred (const QString &error)
void messageSent (const QString &message)
Public Member Functions
NetworkManager (QObject *parent=nullptr)
void connectToServer (const QString &ip, quint16 port)
void sendMessage (const QString &message)
Private Slots
void onConnected ()
void onDisconnected ()
void onError (QAbstractSocket::SocketError socketError)
void onSocketReadyRead ()
Private Attributes
QTcpSocket * socket_
Constructor & Destructor Documentation
NetworkManager()
NetworkManager::NetworkManager (QObject * parent = nullptr) [explicit]
References onConnected(), onDisconnected(), onError(), TTTController::onSocketReadyRead(), and socket_.
Member Function Documentation
connected
void NetworkManager::connected () [signal]
Referenced by onConnected().
connectToServer()
void NetworkManager::connectToServer (const QString & ip, quint16 port)
References socket_.
disconnected
void NetworkManager::disconnected () [signal]
Referenced by onDisconnected().
errorOccurred
void NetworkManager::errorOccurred (const QString & error) [signal]
Referenced by onError(), and sendMessage().
messageSent
void NetworkManager::messageSent (const QString & message) [signal]
Referenced by sendMessage().
onConnected
void NetworkManager::onConnected () [private], [slot]
References connected().
Referenced by NetworkManager().
onDisconnected
void NetworkManager::onDisconnected () [private], [slot]
References disconnected().
Referenced by NetworkManager().
onError
void NetworkManager::onError (QAbstractSocket::SocketError socketError) [private], [slot]
References errorOccurred(), and socket_.
Referenced by NetworkManager().
onSocketReadyRead
void NetworkManager::onSocketReadyRead () [private], [slot]
References socket_.
sendMessage()
void NetworkManager::sendMessage (const QString & message)
References errorOccurred(), messageSent(), and socket_.
Member Data Documentation
socket_
QTcpSocket* NetworkManager::socket_ [private]
Referenced by connectToServer(), NetworkManager(), onError(), onSocketReadyRead(), and sendMessage().
The documentation for this class was generated from the following files:
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/Network/NetworkManager.h
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/Network/NetworkManager.cpp