TitleScreen Class Reference
The TitleScreen class is responsible for the GUI of the title screen, its main functionality is to gather game options set by the user, then starting a game by creating a Tic Tac Toe controller with the user options.
#include <TitleScreen.h>
Public Slots
void updateBoardSize (int size)
updateBoardSize updates the board size in the current options.
void updateSinglePlayer (bool checked)
updateSinglePlayer updates the AI existence flag to true as there is one player.
void updateTwoPlayers (bool checked)
updateTwoPlayers updates the AI existence flag to false as there are two player.
void updateAIstartsGame (bool checked)
updateAIstartsGame sets the AI starting the first play or not.
void updateMiniMaxDepth (int depth)
updateMiniMaxDepth sets the value of the depth cutoff for the minimax algorithm.
void startGame ()
startGame hides the title screen and creates a Tic tac toe controller to start a game.
Signals
void exited ()
exited is emitted to manually handle the close functionality.
Public Member Functions
TitleScreen (QWidget *parent=nullptr)
TitleScreen constructs the view of the title screen.
Private Member Functions
void setConnections ()
setConnections sets connections to gather game options from the GUI elements.
void closeEvent (QCloseEvent *event) override
closeEvent manually handles the closing event defined in the base class QWidget.
Private Attributes
std::unique_ptr< Ui::TitleScreen > ui
ui is a reference to the ui object of the tic tac toe game.
TTTOptions options_
options are the values and flags that control a tic tac toe game.
Detailed Description
The TitleScreen class is responsible for the GUI of the title screen, its main functionality is to gather game options set by the user, then starting a game by creating a Tic Tac Toe controller with the user options.
Constructor & Destructor Documentation
TitleScreen()
TitleScreen::TitleScreen (QWidget * parent = nullptr) [explicit]
TitleScreen constructs the view of the title screen.
Parameters
parent is a QWidget type parent that owns this instance of the controller.
References setConnections(), TitleScreen(), and ui.
Referenced by TitleScreen().
Member Function Documentation
closeEvent()
void TitleScreen::closeEvent (QCloseEvent * event) [override], [private]
closeEvent manually handles the closing event defined in the base class QWidget.
Parameters
event the closing event.
References exited().
exited
void TitleScreen::exited () [signal]
exited is emitted to manually handle the close functionality.
Referenced by closeEvent(), and main().
setConnections()
void TitleScreen::setConnections () [private]
setConnections sets connections to gather game options from the GUI elements.
References startGame(), ui, updateAIstartsGame(), updateBoardSize(), updateMiniMaxDepth(), updateSinglePlayer(), and updateTwoPlayers().
Referenced by TitleScreen().
startGame
void TitleScreen::startGame () [slot]
startGame hides the title screen and creates a Tic tac toe controller to start a game.
References options_.
Referenced by setConnections().
updateAIstartsGame
void TitleScreen::updateAIstartsGame (bool checked) [slot]
updateAIstartsGame sets the AI starting the first play or not.
Parameters
checked wether the checkbox is checked or not.
References options_.
Referenced by setConnections().
updateBoardSize
void TitleScreen::updateBoardSize (int size) [slot]
updateBoardSize updates the board size in the current options.
Parameters
size the number of rows or columns in the board.
References options_, and ui.
Referenced by setConnections().
updateMiniMaxDepth
void TitleScreen::updateMiniMaxDepth (int depth) [slot]
updateMiniMaxDepth sets the value of the depth cutoff for the minimax algorithm.
Parameters
depth the depth cutoff for the minimax algorithm.
References options_, and ui.
Referenced by setConnections().
updateSinglePlayer
void TitleScreen::updateSinglePlayer (bool checked) [slot]
updateSinglePlayer updates the AI existence flag to true as there is one player.
Parameters
checked wether the radio button is checked or not.
References options_, and ui.
Referenced by setConnections().
updateTwoPlayers
void TitleScreen::updateTwoPlayers (bool checked) [slot]
updateTwoPlayers updates the AI existence flag to false as there are two player.
Parameters
checked wether the radio button is checked or not.
References options_, and ui.
Referenced by setConnections().
Member Data Documentation
options_
TTTOptions TitleScreen::options_ [private]
options are the values and flags that control a tic tac toe game.
Referenced by startGame(), updateAIstartsGame(), updateBoardSize(), updateMiniMaxDepth(), updateSinglePlayer(), and updateTwoPlayers().
ui
std::unique_ptr<Ui::TitleScreen> TitleScreen::ui [private]
ui is a reference to the ui object of the tic tac toe game.
Referenced by setConnections(), TitleScreen(), updateBoardSize(), updateMiniMaxDepth(), updateSinglePlayer(), and updateTwoPlayers().
The documentation for this class was generated from the following files:
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/View/TitleScreen.h
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/View/TitleScreen.cpp