ConfigManager Class Reference
The ConfigManager class.
#include <ConfigManager.h>
Public Member Functions
void load (const QString &filePath=QString())
Carga el archivo de configuración desde la ruta indicada. Si no se especifica ruta, buscará config.ini en el directorio actual.
QString getValue (const QString &key, const QString &defaultValue=QString()) const
Devuelve un valor del archivo INI como QString.
int getInt (const QString &key, int defaultValue=0) const
Devuelve un valor como entero.
bool getBool (const QString &key, bool defaultValue=false) const
Devuelve un valor como booleano.
Static Public Member Functions
static ConfigManager & instance ()
Obtiene la instancia única del ConfigManager (Singleton).
Private Member Functions
ConfigManager (QObject *parent=nullptr)
~ConfigManager () override=default
ConfigManager (const ConfigManager &)=delete
ConfigManager & operator= (const ConfigManager &)=delete
Private Attributes
QSettings * settings_ = nullptr
Detailed Description
The ConfigManager class.
Gestiona la configuración de la aplicación desde un archivo config.ini. Aplica el patrón Singleton para asegurar que solo existe una instancia accesible globalmente.
Constructor & Destructor Documentation
ConfigManager() [1/2]
ConfigManager::ConfigManager (QObject * parent = nullptr) [explicit], [private]
Referenced by ConfigManager(), instance(), and operator=().
~ConfigManager()
ConfigManager::~ConfigManager () [override], [private], [default]
ConfigManager() [2/2]
ConfigManager::ConfigManager (const ConfigManager &) [private], [delete]
References ConfigManager().
Member Function Documentation
getBool()
bool ConfigManager::getBool (const QString & key, bool defaultValue = false) const
Devuelve un valor como booleano.
References settings_.
getInt()
int ConfigManager::getInt (const QString & key, int defaultValue = 0) const
Devuelve un valor como entero.
References settings_.
getValue()
QString ConfigManager::getValue (const QString & key, const QString & defaultValue = QString()) const
Devuelve un valor del archivo INI como QString.
Parameters
key Clave (por ejemplo, "network/ip")
defaultValue Valor por defecto si no se encuentra la clave
Returns
Valor asociado
References settings_.
instance()
ConfigManager & ConfigManager::instance () [static]
Obtiene la instancia única del ConfigManager (Singleton).
Returns
Referencia al único ConfigManager.
References ConfigManager(), and instance().
Referenced by SpeechManager::configure(), instance(), and main().
load()
void ConfigManager::load (const QString & filePath = QString())
Carga el archivo de configuración desde la ruta indicada. Si no se especifica ruta, buscará config.ini en el directorio actual.
Parameters
filePath Ruta al archivo .ini
References settings_.
Referenced by main().
operator=()
ConfigManager & ConfigManager::operator= (const ConfigManager &) [private], [delete]
References ConfigManager().
Member Data Documentation
settings_
QSettings* ConfigManager::settings_ = nullptr [private]
Referenced by getBool(), getInt(), getValue(), and load().
The documentation for this class was generated from the following files:
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/Config/ConfigManager.h
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/Config/ConfigManager.cpp