TicTacToeGame Class Reference
The TicTacToeGame class is responsible for the GUI of a game, it is responsible for building the cells of a board, which can be of variable size, and a navigation button to take the user back to the title screen, and a button for resetting the game and playing a new one.
#include <TicTacToeGame.h>
Signals
void newGame ()
newGame is emitted when the New Game button is clicked and some reset logic must be executed.
Public Member Functions
TicTacToeGame (QWidget *parent=nullptr)
TicTacToeGame constructs a view of a game.
void updateCell (Cell &cell, BoardMarks currentPlayer)
updateCell sets the Text of the cell to the current player's mark.
void declareGameState (BoardState boardState)
declareGameState outputs the board's state to a QMessageBox.
vector< Cell > buildCellButtons (size_t boardSize)
buildCellButtons builds the GUI cells as push buttons.
void reset (vector< Cell > &cells)
reset clears out the text of all push button cells.
Private Member Functions
void setConnections ()
setConnections handles setting the connection to emit if cells have cliked, and the navigational back button.
QString getPlayerText (BoardMarks currentPlayer)
getPlayerText converts a board mark to a QString.
QString getPlayerStyleSheet (BoardMarks currentPlayer)
getPlayerStyleSheet gets a stylesheet associated with each player.
QString getBoardFinalStateText (BoardState boardState)
getBoardFinalStateText converts a state to a decleration text, that will be used when declaring the final state of a game.
Private Attributes
std::unique_ptr< Ui::TicTacToeGame > ui
ui is a reference to the ui object of the tic tac toe game.
Detailed Description
The TicTacToeGame class is responsible for the GUI of a game, it is responsible for building the cells of a board, which can be of variable size, and a navigation button to take the user back to the title screen, and a button for resetting the game and playing a new one.
Constructor & Destructor Documentation
TicTacToeGame()
TicTacToeGame::TicTacToeGame (QWidget * parent = nullptr) [explicit]
TicTacToeGame constructs a view of a game.
Parameters
parent is a QWidget type parent that owns this instance of the controller.
References setConnections(), TicTacToeGame(), and ui.
Referenced by TicTacToeGame().
Member Function Documentation
buildCellButtons()
vector< Cell > TicTacToeGame::buildCellButtons (size_t boardSize)
buildCellButtons builds the GUI cells as push buttons.
Parameters
boardSize number of rows or columns of a board.
Returns
a collection of cells containing push button references and their corresponding row and column.
References defaults::GUI_CELL_COLUMN_SPAN, defaults::GUI_CELL_ROW_SPAN, and ui.
declareGameState()
void TicTacToeGame::declareGameState (BoardState boardState)
declareGameState outputs the board's state to a QMessageBox.
Parameters
boardState the current board state.
References getBoardFinalStateText().
getBoardFinalStateText()
QString TicTacToeGame::getBoardFinalStateText (BoardState boardState) [private]
getBoardFinalStateText converts a state to a decleration text, that will be used when declaring the final state of a game.
Parameters
boardState the current board state.
Returns
QString decleration text, that will be used when declaring the final state of a game.
References OWins, Tie, and XWins.
Referenced by declareGameState().
getPlayerStyleSheet()
QString TicTacToeGame::getPlayerStyleSheet (BoardMarks currentPlayer) [private]
getPlayerStyleSheet gets a stylesheet associated with each player.
Parameters
currentPlayer the current player's mark (X or O).
Returns
a QString stylesheet of the player given in the input.
References defaults::DEFAULT_COLOR, O, defaults::O_COLOR, X, and defaults::X_COLOR.
Referenced by updateCell().
getPlayerText()
QString TicTacToeGame::getPlayerText (BoardMarks currentPlayer) [private]
getPlayerText converts a board mark to a QString.
Parameters
currentPlayer the current player's mark (X or O).
Returns
a QString of the player's mark.
References O, and X.
Referenced by updateCell().
newGame
void TicTacToeGame::newGame () [signal]
newGame is emitted when the New Game button is clicked and some reset logic must be executed.
Referenced by TTTController::setConnections().
reset()
void TicTacToeGame::reset (vector< Cell > & cells)
reset clears out the text of all push button cells.
Parameters
cells a collection of cells containing push button references and their corresponding row and column.
setConnections()
void TicTacToeGame::setConnections () [private]
setConnections handles setting the connection to emit if cells have cliked, and the navigational back button.
References ui.
Referenced by TicTacToeGame().
updateCell()
void TicTacToeGame::updateCell (Cell & cell, BoardMarks currentPlayer)
updateCell sets the Text of the cell to the current player's mark.
Parameters
cell a refernece to the clicked cell.
currentPlayer the current player's mark (X or O).
References Cell::cellBtn, getPlayerStyleSheet(), and getPlayerText().
Member Data Documentation
ui
std::unique_ptr<Ui::TicTacToeGame> TicTacToeGame::ui [private]
ui is a reference to the ui object of the tic tac toe game.
Referenced by buildCellButtons(), setConnections(), and TicTacToeGame().
The documentation for this class was generated from the following files:
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/View/TicTacToeGame.h
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/View/TicTacToeGame.cpp