Board Class Reference
The Board class is responsible for representing the underlying model of the game, it is a 2D matrix representation of the GUI that is machine readable, and can be used when running any sort of algorithms on the board.
#include <Board.h>
Public Member Functions
Board (size_t size)
Constructs a board given a board size.
Board (Board &b)
Board copy constructor.
Board (const Board &b)
Board (Board &&b)
Board move constructor.
Board & operator= (Board b)
This assignment operator implements the copy & swap idiom, so it works as a move and a copy assignment operator.
virtual ~Board ()
Board destructor.
virtual BoardState evaluateBoard () const
evaluateBoard evaluates whether the state of the current board. the function can evaluate to X wins or O wins or a Tie or No Winner.
virtual bool setPlayerInput (size_t row, size_t col, BoardMarks currentPlayer)
setPlayerInput sets the board with the mark given in the specified location. after boundary checking the input row and column, and if the game hasen't reached a final state.
virtual BoardMarks at (size_t row, size_t col) const
at is a getter function that returns a cell given a row and a column.
virtual void reset ()
reset allows resetting the whole board, marking all the cells as empty.
virtual void resetCell (size_t row, size_t col)
resetCell allows resetting a given cell to an empty type, without the extra state checks done in the setPlayerInput function.
size_t size () const
size is a getter functions of the board size.
Protected Attributes
vector< vector< BoardMarks > > board_
board is a 2D vector that represents a machine readable format to the GUI application.
size_t boardSize_
boardSize is the number of rows or columns in the board. a 3x3 board has a boardSize of 3.
Detailed Description
The Board class is responsible for representing the underlying model of the game, it is a 2D matrix representation of the GUI that is machine readable, and can be used when running any sort of algorithms on the board.
Constructor & Destructor Documentation
Board() [1/4]
Board::Board (size_t size)
Constructs a board given a board size.
Parameters
size is the number of rows or columns in the board.
References board_, boardSize_, and size().
Referenced by Board(), Board(), Board(), and operator=().
Board() [2/4]
Board::Board (Board & b)
Board copy constructor.
Parameters
b The board to be copied.
References Board(), board_, and boardSize_.
Board() [3/4]
Board::Board (const Board & b)
References Board(), board_, and boardSize_.
Board() [4/4]
Board::Board (Board && b)
Board move constructor.
Parameters
b The board to be moved.
References Board(), board_, and boardSize_.
~Board()
Board::~Board () [virtual]
Board destructor.
Member Function Documentation
at()
BoardMarks Board::at (size_t row, size_t col) const [virtual]
at is a getter function that returns a cell given a row and a column.
Parameters
row of the cell target.
col of the cell target.
Returns
the value mark at the cell.
Exceptions
out_of_range exception when the row or column is out of bounds.
References board_.
Referenced by MiniMaxAgent::maxMove(), MiniMaxAgent::minMove(), MiniMaxAgent::play(), TEST(), TEST(), TEST(), TEST(), and TEST().
evaluateBoard()
BoardState Board::evaluateBoard () const [virtual]
evaluateBoard evaluates whether the state of the current board. the function can evaluate to X wins or O wins or a Tie or No Winner.
Returns
the state of the current board.
References board_, boardSize_, Empty, NoWinner, O, OWins, Tie, X, and XWins.
Referenced by MiniMaxAgent::maxMove(), MiniMaxAgent::minMove(), MiniMaxAgent::play(), setPlayerInput(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
operator=()
Board & Board::operator= (Board b)
This assignment operator implements the copy & swap idiom, so it works as a move and a copy assignment operator.
Parameters
b The board to be copied or moved.
Returns
a reference to this object, so this operator can be chained.
References Board(), board_, and boardSize_.
reset()
void Board::reset () [virtual]
reset allows resetting the whole board, marking all the cells as empty.
References board_, boardSize_, and Empty.
Referenced by TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
resetCell()
void Board::resetCell (size_t row, size_t col) [virtual]
resetCell allows resetting a given cell to an empty type, without the extra state checks done in the setPlayerInput function.
References board_, boardSize_, and Empty.
Referenced by MiniMaxAgent::maxMove(), MiniMaxAgent::minMove(), and MiniMaxAgent::play().
setPlayerInput()
bool Board::setPlayerInput (size_t row, size_t col, BoardMarks currentPlayer) [virtual]
setPlayerInput sets the board with the mark given in the specified location. after boundary checking the input row and column, and if the game hasen't reached a final state.
Parameters
row of the cell target.
col of the cell target.
currentPlayer is the mark of the current player.
Returns
whether the update was successfull or not based on the boundary check and validity of input given the board state.
Exceptions
out_of_range exception when the row or column is out of bounds.
References board_, boardSize_, Empty, evaluateBoard(), and NoWinner.
Referenced by MiniMaxAgent::maxMove(), MiniMaxAgent::minMove(), MiniMaxAgent::play(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
size()
size_t Board::size () const
size is a getter functions of the board size.
Returns
the size of the board i.e. numebr of rows or columns.
References boardSize_.
Referenced by Board(), MiniMaxAgent::maxMove(), MiniMaxAgent::minMove(), and MiniMaxAgent::play().
Member Data Documentation
board_
vector<vector<BoardMarks> > Board::board_ [protected]
board is a 2D vector that represents a machine readable format to the GUI application.
Referenced by at(), Board(), Board(), Board(), Board(), evaluateBoard(), operator=(), reset(), resetCell(), and setPlayerInput().
boardSize_
size_t Board::boardSize_ [protected]
boardSize is the number of rows or columns in the board. a 3x3 board has a boardSize of 3.
Referenced by Board(), Board(), Board(), Board(), evaluateBoard(), operator=(), reset(), resetCell(), setPlayerInput(), and size().
The documentation for this class was generated from the following files:
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/Model/Board.h
C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/Model/Board.cpp