C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/TicTacToeTest/tst_minimaxagent.h File Reference
#include <gtest/gtest.h>
#include <gmock/gmock-matchers.h>
#include "Board.h"
#include "MiniMaxAgent.h"
Functions
TEST (MiniMaxAgentTest, PlayerStartAIWin)
TEST (MiniMaxAgentTest, AIStartAIWin)
TEST (MiniMaxAgentTest, PlayerStartAIBlock)
TEST (MiniMaxAgentTest, AIStartAIBlock)
Function Documentation
TEST() [1/4]
TEST (MiniMaxAgentTest , AIStartAIBlock)
References Board::at(), Empty, O, MiniMaxAgent::play(), Board::reset(), Board::setPlayerInput(), and X.
TEST() [2/4]
TEST (MiniMaxAgentTest , AIStartAIWin)
References Empty, Board::evaluateBoard(), O, MiniMaxAgent::play(), Board::reset(), Board::setPlayerInput(), X, and XWins.
TEST() [3/4]
TEST (MiniMaxAgentTest , PlayerStartAIBlock)
References Board::at(), Empty, O, MiniMaxAgent::play(), Board::reset(), Board::setPlayerInput(), and X.
TEST() [4/4]
TEST (MiniMaxAgentTest , PlayerStartAIWin)
References Empty, Board::evaluateBoard(), O, OWins, MiniMaxAgent::play(), Board::reset(), Board::setPlayerInput(), and X.