C:/Users/ferna/Voice_TicTacToe/Qt-Tic-Tac-Toe-master/TicTacToeTest/tst_board.h File Reference
#include <gtest/gtest.h>
#include <gmock/gmock-matchers.h>
#include "Board.h"
Functions
TEST (BoardTest, resetBoard)
TEST (BoardTest, evaluateBoardXWins3x3)
TEST (BoardTest, evaluateBoardOWins3x3)
TEST (BoardTest, evaluateBoardTie3x3)
TEST (BoardTest, evaluateBoardNoWinner3x3)
TEST (BoardTest, setPlayerInputValid)
TEST (BoardTest, setPlayerInputOutOfBounds)
TEST (BoardTest, setPlayerInputOverwrite)
TEST (BoardTest, setPlayerInputAfterGameOver)
TEST (BoardTest, boardAccessValid)
TEST (BoardTest, boardAccessInValid)
Function Documentation
TEST() [1/11]
TEST (BoardTest , boardAccessInValid)
References Board::at().
TEST() [2/11]
TEST (BoardTest , boardAccessValid)
References Board::at(), Empty, O, Board::setPlayerInput(), and X.
TEST() [3/11]
TEST (BoardTest , evaluateBoardNoWinner3x3)
References Empty, Board::evaluateBoard(), NoWinner, O, Board::reset(), Board::setPlayerInput(), and X.
TEST() [4/11]
TEST (BoardTest , evaluateBoardOWins3x3)
References Empty, Board::evaluateBoard(), O, OWins, Board::reset(), Board::setPlayerInput(), and X.
TEST() [5/11]
TEST (BoardTest , evaluateBoardTie3x3)
References Board::evaluateBoard(), O, Board::reset(), Board::setPlayerInput(), Tie, and X.
TEST() [6/11]
TEST (BoardTest , evaluateBoardXWins3x3)
References Empty, Board::evaluateBoard(), O, Board::reset(), Board::setPlayerInput(), X, and XWins.
TEST() [7/11]
TEST (BoardTest , resetBoard)
References Board::at(), Empty, O, Board::reset(), Board::setPlayerInput(), and X.
TEST() [8/11]
TEST (BoardTest , setPlayerInputAfterGameOver)
References Empty, O, Board::reset(), Board::setPlayerInput(), and X.
TEST() [9/11]
TEST (BoardTest , setPlayerInputOutOfBounds)
References Board::setPlayerInput(), and X.
TEST() [10/11]
TEST (BoardTest , setPlayerInputOverwrite)
References O, Board::setPlayerInput(), and X.
TEST() [11/11]
TEST (BoardTest , setPlayerInputValid)
References Board::setPlayerInput(), and X.