# CMake generated Testfile for 
# Source directory: /home/ratty/Downloads/pocketsphinx-main/test/unit
# Build directory: /home/ratty/Downloads/pocketsphinx-main/examples/test/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_acmod "/home/ratty/Downloads/pocketsphinx-main/examples/test_acmod")
set_tests_properties(test_acmod PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_acmod_grow "/home/ratty/Downloads/pocketsphinx-main/examples/test_acmod_grow")
set_tests_properties(test_acmod_grow PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_alignment "/home/ratty/Downloads/pocketsphinx-main/examples/test_alignment")
set_tests_properties(test_alignment PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_allphone "/home/ratty/Downloads/pocketsphinx-main/examples/test_allphone")
set_tests_properties(test_allphone PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_bitvec "/home/ratty/Downloads/pocketsphinx-main/examples/test_bitvec")
set_tests_properties(test_bitvec PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_config "/home/ratty/Downloads/pocketsphinx-main/examples/test_config")
set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_dict2pid "/home/ratty/Downloads/pocketsphinx-main/examples/test_dict2pid")
set_tests_properties(test_dict2pid PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_dict "/home/ratty/Downloads/pocketsphinx-main/examples/test_dict")
set_tests_properties(test_dict PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_dict_strcat "/home/ratty/Downloads/pocketsphinx-main/examples/test_dict_strcat")
set_tests_properties(test_dict_strcat PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_fe "/home/ratty/Downloads/pocketsphinx-main/examples/test_fe")
set_tests_properties(test_fe PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_fe_warp_overflow "/home/ratty/Downloads/pocketsphinx-main/examples/test_fe_warp_overflow")
set_tests_properties(test_fe_warp_overflow PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_fwdflat "/home/ratty/Downloads/pocketsphinx-main/examples/test_fwdflat")
set_tests_properties(test_fwdflat PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_fwdtree_bestpath "/home/ratty/Downloads/pocketsphinx-main/examples/test_fwdtree_bestpath")
set_tests_properties(test_fwdtree_bestpath PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_fwdtree "/home/ratty/Downloads/pocketsphinx-main/examples/test_fwdtree")
set_tests_properties(test_fwdtree PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_init "/home/ratty/Downloads/pocketsphinx-main/examples/test_init")
set_tests_properties(test_init PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_jsgf "/home/ratty/Downloads/pocketsphinx-main/examples/test_jsgf")
set_tests_properties(test_jsgf PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_keyphrase "/home/ratty/Downloads/pocketsphinx-main/examples/test_keyphrase")
set_tests_properties(test_keyphrase PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_lattice "/home/ratty/Downloads/pocketsphinx-main/examples/test_lattice")
set_tests_properties(test_lattice PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_lm_convert "/home/ratty/Downloads/pocketsphinx-main/examples/test_lm_convert")
set_tests_properties(test_lm_convert PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_ngram_model_read "/home/ratty/Downloads/pocketsphinx-main/examples/test_ngram_model_read")
set_tests_properties(test_ngram_model_read PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_log_shifted "/home/ratty/Downloads/pocketsphinx-main/examples/test_log_shifted")
set_tests_properties(test_log_shifted PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_log_int8 "/home/ratty/Downloads/pocketsphinx-main/examples/test_log_int8")
set_tests_properties(test_log_int8 PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_log_int16 "/home/ratty/Downloads/pocketsphinx-main/examples/test_log_int16")
set_tests_properties(test_log_int16 PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_mllr "/home/ratty/Downloads/pocketsphinx-main/examples/test_mllr")
set_tests_properties(test_mllr PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_nbest "/home/ratty/Downloads/pocketsphinx-main/examples/test_nbest")
set_tests_properties(test_nbest PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_pitch "/home/ratty/Downloads/pocketsphinx-main/examples/test_pitch")
set_tests_properties(test_pitch PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_posterior "/home/ratty/Downloads/pocketsphinx-main/examples/test_posterior")
set_tests_properties(test_posterior PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_ptm_mgau "/home/ratty/Downloads/pocketsphinx-main/examples/test_ptm_mgau")
set_tests_properties(test_ptm_mgau PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_reinit "/home/ratty/Downloads/pocketsphinx-main/examples/test_reinit")
set_tests_properties(test_reinit PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_senfh "/home/ratty/Downloads/pocketsphinx-main/examples/test_senfh")
set_tests_properties(test_senfh PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_set_search "/home/ratty/Downloads/pocketsphinx-main/examples/test_set_search")
set_tests_properties(test_set_search PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_simple "/home/ratty/Downloads/pocketsphinx-main/examples/test_simple")
set_tests_properties(test_simple PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_state_align "/home/ratty/Downloads/pocketsphinx-main/examples/test_state_align")
set_tests_properties(test_state_align PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_vad "/home/ratty/Downloads/pocketsphinx-main/examples/test_vad")
set_tests_properties(test_vad PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_vad_alloc "/home/ratty/Downloads/pocketsphinx-main/examples/test_vad_alloc")
set_tests_properties(test_vad_alloc PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_word_align "/home/ratty/Downloads/pocketsphinx-main/examples/test_word_align")
set_tests_properties(test_word_align PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_endpointer "/home/ratty/Downloads/pocketsphinx-main/examples/test_endpointer")
set_tests_properties(test_endpointer PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_endpointer_timestamp "/home/ratty/Downloads/pocketsphinx-main/examples/test_endpointer_timestamp")
set_tests_properties(test_endpointer_timestamp PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_thread_local_compile "/home/ratty/Downloads/pocketsphinx-main/examples/test_thread_local_compile")
set_tests_properties(test_thread_local_compile PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_thread_local_basic "/home/ratty/Downloads/pocketsphinx-main/examples/test_thread_local_basic")
set_tests_properties(test_thread_local_basic PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_thread_utils_self "/home/ratty/Downloads/pocketsphinx-main/examples/test_thread_utils_self")
set_tests_properties(test_thread_utils_self PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_genrand_baseline "/home/ratty/Downloads/pocketsphinx-main/examples/test_genrand_baseline")
set_tests_properties(test_genrand_baseline PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_genrand_thread "/home/ratty/Downloads/pocketsphinx-main/examples/test_genrand_thread")
set_tests_properties(test_genrand_thread PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
add_test(test_genrand_thread_tls "/home/ratty/Downloads/pocketsphinx-main/examples/test_genrand_thread_tls")
set_tests_properties(test_genrand_thread_tls PROPERTIES  _BACKTRACE_TRIPLES "/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;60;add_test;/home/ratty/Downloads/pocketsphinx-main/test/unit/CMakeLists.txt;0;")
subdirs("test_alloc")
subdirs("test_case")
subdirs("test_feat")
subdirs("test_fsg")
subdirs("test_hash")
subdirs("test_lineiter")
subdirs("test_matrix")
subdirs("test_ngram")
subdirs("test_string")
subdirs("test_util")
